### ISSUE TITLE
[Bug]: Object tankerkoenig.0.stations.cheapest.diesel.postCode is invalid: Default value has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.tankerkoenig#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Warnmeldung im Log beim Start des Adapters:
Object tankerkoenig.0.stations.cheapest.diesel.postCode is invalid: Default value has to be type "number" but received type "string"
This object will not be created in future versions. Please report this to the developer

Im Betrieb kommt eine Info-Meldung:
State value to set for "tankerkoenig.0.stations.1.postCode" has to be type "number" but received type "string"
State value to set for "tankerkoenig.0.stations.0.postCode" has to be type "number" but received type "string"

### Adapter version

3.2.3

### Environment

```markdown
- Node:16.19.0
- npm:8.19.3
- JS-Controller:4.0.24
- Operating system:debian 11
```

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by xXBJXx** [comment]
Hattest du vorher schon eine Version ab 3.2.0 installiert
dann bitte den state ein mal löschen und Adapter neu starten

**Comment by xXBJXx** [comment]
Sobald das Update verfügbar ist, die states `postCode` löschen und das Update aufspielen

**Comment by guergen1** [comment]
Ja, ich hatte die alten Versionen auch schon laufen. Habe händisch die States gelöscht und neu anlegen lassen, das ging nicht, daher das Issue...

**Comment by xXBJXx** [comment]
Habe es gestern, als ich die detaillierte Anfrage entfernt habe, komplett vergessen, dass der state jetzt ein string ist und keine Nummer

**Comment by xXBJXx** [comment]
Das Update sollte in ein paar Stunden im latest verfügbar sein

**Comment by guergen1** [comment]
Ist ja kein Problem, dazu gibt es ja die Issues.
Aber ich warte das Update ab, sonst muss ich bei allen PostCodes den Wert ändern ;-)

**Comment by xXBJXx** [comment]
Beim update, musst du die states löschen und neu generieren lasen

**Comment by guergen1** [comment]
Ist klar!

**Comment by guergen1** [comment]
Läuft
