### ISSUE TITLE
type error 

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.tankerkoenig#103]
`[ Adapter V:3.3.0 writeState ] error: TypeError: Cannot read properties of undefined (reading 'toString') stack: TypeError: Cannot read properties of undefined (reading 'toString') at Tankerkoenig.writeState (/opt/iobroker/node_modules/iobroker.tankerkoenig/src/main.ts:582:34) at Tankerkoenig.requestData (/opt/iobroker/node_modules/iobroker.tankerkoenig/src/main.ts:156:6) at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.tankerkoenig/src/main.ts:189:5)`

**Comment by xXBJXx** [comment]
After the update, you have to go to the UI again and then click on 
![image](https://user-images.githubusercontent.com/32600934/210060779-e2cc4099-8861-4404-8da1-3eac1aab1328.png)
and copy the ID once again, so that the data is taken over correctly, by clicking on add and save.

**Comment by xXBJXx** [comment]
Please delete `tankerkoenig.0.stations.x.postCode` and `tankerkoenig.0.stations.cheapest.x.postCode` and restart adapter, type has changed from string to number.
