### ISSUE TITLE
[Bug]: V3.3.0:Hausnummer wird nicht im Hausnummer-Feld eingetragen

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.tankerkoenig#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Die Hausnummer wird nicht im Hausnummer-Feld eingetragen, wenn ich eine neue Tankstelle mit Hilfe des Tankstellenfinders eintrage

### Adapter version

3.3.0

### Environment

```markdown
- Node:16.19.0
- npm:8.19.3
- JS-Controller:4.0.24
- Operating system: Dewbian 11
```

### Screenshots & Log

![grafik](https://user-images.githubusercontent.com/34395245/210067221-b1a037c8-a4ef-48f5-bb6a-d1acf8fbdf68.png)

**Comment by xXBJXx** [comment]
das ist kein bug da die hausnummer von der station nicht über geben wird sondern direkt in der straße steht 
![image](https://user-images.githubusercontent.com/32600934/210068979-9a09af9c-ccfb-4409-98fc-5b14f5edef93.png)

**Comment by xXBJXx** [comment]
Das mit der Hausnummer ist nicht schlimm entweder man schreibt es selbst rein oder lässt es so das wird im Adapter abgefangen

PS. Mit der `Version 3.3.1` muss der `tankerkoenig.0.stations.x.postCode` gelöscht und neu erstellt werden, da jetzt die Daten von Tankerkönig kommen und dort ist es eine Nummer und kein Text deshalb habe ich den state auf Nummer geändert.

**Comment by guergen1** [comment]
Nein, schlimm ist es nicht, nur ein optischer Fehler. Ich weiss ja nicht, ob es evtl im weiteren Verlauf zu einem Fehler führen könnte
OK, also wieder zurück zur Nummer ;-) Kein Problem!

**Comment by guergen1** [comment]
Muss nochmal nerven: hab grade die 3.3.1 von git gezogen.
Da scheint noch was mit "string-number" nicht zu passen:
State value to set for "tankerkoenig.0.stations.3.postCode" has to be type "number" but received type "string"

**Comment by xXBJXx** [comment]
Schaue mal unter 
system.adapter.tankerkoenig.0 ob du da die `"postCode": 59846` oder `"postCode": "59846"` stehen hast
![image](https://user-images.githubusercontent.com/32600934/210077323-f760e9ea-6d2f-4c4d-bbad-786132f9a4aa.png)
![image](https://user-images.githubusercontent.com/32600934/210077278-f9b09813-03ef-496f-a089-4351a52cb98b.png)

**Comment by guergen1** [comment]
Ich glaube hier steht das mit " drin

`{
  "_id": "system.adapter.tankerkoenig.0",
  "type": "instance",
  "common": {
    "name": "tankerkoenig",
    "title": "Tankerkönig Spritpreise",
    "titleLang": {
      "en": "Tankerkoenig Fuel prices",
      "de": "Tankerkönig Spritpreise",
      "ru": "Tankerkoenig Цены на топливо",
      "pt": "Preços de combustível Tankerkoenig",
      "nl": "Tankerkoenig Brandstofprijzen",
      "fr": "Prix du carburant Tankerkoenig",
      "it": "Prezzi del carburante Tankerkoenig",
      "es": "Precios del combustible Tankerkoenig",
      "pl": "Tankerkoenig Ceny paliwa",
      "zh-cn": "Tankerkoenig燃料价格",
      "uk": "Tankerkoenig Ціни на паливо"
    },
    "desc": {
      "en": "Tankerkoenig fuel prices",
      "de": "Tankerkönig Spritpreise",
      "ru": "Tankerkoenig Цены на топливо",
      "pt": "Preços de combustível Tankerkoenig",
      "nl": "Tankerkoenig Brandstofprijzen",
      "fr": "Prix du carburant Tankerkoenig",
      "it": "Prezzi del carburante Tankerkoenig",
      "es": "Precios del combustible Tankerkoenig",
      "pl": "Tankerkoenig Ceny paliwa",
      "uk": "Tankerkoenig Ціни на паливо",
      "zh-cn": "Tankerkoenig燃料价格"
    },
    "version": "3.3.1",
    "mode": "daemon",
    "platform": "Javascript/Node.js",
    "loglevel": "info",
    "compact": true,
    "keywords": [
      "fuel",
      "gas",
      "tankerkoenig",
      "Tankerkönig",
      "Sprit",
      "Spritpreis",
      "Tankstelle",
      "Diesel",
      "Benzin"
    ],
    "main": "build/main.js",
    "authors": [
      {
        "name": "pix"
      },
      {
        "name": "xXBJXx",
        "email": "issi.dev.iobroker@gmail.com"
      }
    ],
    "license": "MIT",
    "readme": "https://github.com/iobroker-community-adapters/ioBroker.tankerkoenig/blob/master/README.md",
    "icon": "tankerkoenig.png",
    "extIcon": "https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.tankerkoenig/master/admin/tankerkoenig.png",
    "allowInit": true,
    "type": "vehicle",
    "materialize": true,
    "config": {
      "width": 850,
      "height": 650,
      "minWidth": 650,
      "minHeight": 400
    },
    "installedVersion": "3.3.1",
    "enabled": true,
    "host": "iob",
    "installedFrom": "iobroker-community-adapters/ioBroker.tankerkoenig#74b28cb39439d083960eb42117bef17ea78baa5b",
    "docs": {
      "en": "docs/en/doc_tankerkoenig_en.md",
      "de": "docs/de/doc_tankerkoenig_de.md"
    },
    "news": {
      "2.0.11": {
        "en": "\"ack flag\" and \"wrong type\" issues coming up due to js-controller upgrade 3.3 were fixed",
        "de": "Probleme mit \"ack flag\" und \"false type\" aufgrund von js-controller upgrade 3.3 wurden behoben",
        "ru": "Исправлены проблемы с \"флагом подтверждения\" и \"неправильным типом\", возникающие в связи с обновлением js-controller 3.3.",
        "pt": "Os problemas de \"ack flag\" e \"tipo incorreto\" que surgiam devido à atualização 3.3 do js-controller foram corrigidos",
        "nl": "\"ack flag\" en \"verkeerde type\" problemen die aan de orde kwamen als gevolg van de js-controller upgrade 3.3 waren opgelost",
        "fr": "Les problèmes de «drapeau d'ack» et de «type incorrect» à venir en raison de la mise à jour 3.3 du contrôleur js ont été corrigés",
        "it": "Sono stati risolti i problemi di \"flag ack\" e \"tipo sbagliato\" dovuti all'aggiornamento 3.3 di js-controller",
        "es": "Se solucionaron los problemas de \"bandera ack\" y \"tipo incorrecto\" debido a la actualización 3.3 del controlador js",
        "pl": "Naprawiono problemy z flagą ACK i złym typem pojawiające się w związku z aktualizacją js-controller do wersji 3.3",
        "zh-cn": "修复了由于js-controller升级3.3而出现的“ ack标志”和“错误类型”问题"
      },
      "2.0.10": {
        "en": "\"has no existing object\" issue fixed",
        "de": "Problem \"hat kein vorhandenes Objekt\" behoben",
        "ru": "Исправлена проблема \"не имеет существующего объекта\"",
        "pt": "Problema \"não tem objeto existente\" corrigido",
        "nl": "\"heeft geen bestaand object\" probleem opgelost",
        "fr": "Problème \"n'a aucun objet existant\" résolu",
        "it": "Problema \"non ha oggetto esistente\" risolto",
        "es": "Problema \"no tiene ningún objeto existente\" solucionado",
        "pl": "Naprawiono problem \"nie ma istniejącego obiektu\"",
        "zh-cn": "修复\"没有对象\"的问题"
      },
      "2.0.9": {
        "en": "NodeJS 10 or higher required",
        "de": "NodeJS 10 oder höher erforderlich",
        "ru": "Требуется NodeJS 10 или выше",
        "pt": "Necessário NodeJS 10 ou superior",
        "nl": "NodeJS 10 of hoger vereist",
        "fr": "NodeJS 10 ou supérieur requis",
        "it": "Nodo JS 10 o superiore richiesto",
        "es": "Nodo JS 10 o superior requerido",
        "pl": "Wymagany NodeJS 10 lub wyższy",
        "zh-cn": "需要NodeJS 10或更高版本"
      },
      "2.0.8": {
        "en": "fixed issue when api reports no data ",
        "de": "Problem behoben, wenn API keine Daten meldet",
        "ru": "исправлена проблема, когда API не сообщает данных",
        "pt": "Foi corrigido um problema quando a API não informa dados",
        "nl": "opgelost probleem wanneer api geen gegevens rapporteert",
        "fr": "correction d'un problème lorsque l'api ne signale aucune donnée",
        "it": "risolto problema quando api non riportava dati",
        "es": "problema solucionado cuando la API no informa datos",
        "pl": "naprawiono problem, gdy API nie zgłasza danych",
        "zh-cn": "修复了api报告无数据时的问题"
      },
      "2.0.7": {
        "en": "Catch error if station status reports 'no stations'",
        "de": "Fangfehler, wenn der Stationsstatus 'keine Stationen' meldet",
        "ru": "Ошибка перехвата, если статус станции сообщает «нет станций»",
        "pt": "Erro de captura se o status da estação relatar 'sem estações'",
        "nl": "Vangstfout als stationstatus 'geen stations' meldt",
        "fr": "Erreur de capture si l'état de la station signale «aucune station»",
        "it": "Errore di cattura se lo stato della stazione riporta 'nessuna stazione'",
        "es": "Error de captura si el estado de la estación informa 'no hay estaciones'",
        "pl": "Błąd połowu, jeśli status stacji zgłasza „brak stacji”",
        "zh-cn": "如果站状态报告“无站”，则捕获错误"
      },
      "1.3.1": {
        "en": "request issues fixed",
        "de": "Anforderungsprobleme behoben",
        "ru": "исправлены проблемы с запросом",
        "pt": "solicitar problemas corrigidos",
        "nl": "verzoek problemen opgelost",
        "fr": "problèmes de demande résolus",
        "it": "richiedere problemi risolti",
        "es": "problemas de solicitud solucionados",
        "pl": "Naprawiono problemy z prośbą",
        "zh-cn": "请求问题已修复"
      },
      "2.1.1": {
        "en": "New adapter category \"vehicle\", NodeJS v16 testing",
        "de": "Neue Adapterkategorie \"Fahrzeug\", NodeJS v16 Test",
        "ru": "Новая категория адаптера \"автомобиль\"",
        "pt": "Nova categoria de adaptador \"veículo\"",
        "nl": "Nieuwe adapter categorie \"voertuig\"",
        "fr": "Nouvel adaptateur catégorie \"véhicule\"",
        "it": "Nuova categoria di adattatori \"veicolo\"",
        "es": "Nueva categoría de adaptador \"vehículo\"",
        "pl": "Nowa kategoria adapterów „pojazd”",
        "zh-cn": "新的适配器类别“车辆”"
      }
    },
    "connectionType": "cloud",
    "dataSource": "poll",
    "stopBeforeUpdate": true,
    "eraseOnUpload": true,
    "dependencies": [
      {
        "js-controller": ">=3.0.0"
      }
    ],
    "globalDependencies": [
      {
        "admin": ">=5.3.3"
      }
    ],
    "messages": [
      {
        "condition": {
          "operand": "and",
          "rules": [
            "oldVersion<3.0.0",
            "newVersion>=3.0.0"
          ]
        },
        "title": {
          "en": "Important notice!",
          "de": "Wichtiger Hinweis!",
          "ru": "Важное замечание!",
          "pt": "Notícia importante!",
          "nl": "Belangrijke mededeling!",
          "fr": "Avis important!",
          "it": "Avviso IMPORTANTE!",
          "es": "Noticia importante!",
          "pl": "Ważna uwaga!",
          "uk": "Важлива замітка!",
          "zh-cn": "重要通知!"
        },
        "text": {
          "en": "The adapter has been reprogrammed from scratch, which means the old config is no longer compatible with the new version. The stations must all be created again.",
          "de": "Der Adapter wurde von Grund auf neu programmiert, was bedeutet, dass die alte Konfiguration nicht mehr mit der neuen Version kompatibel ist. Die Stationen müssen alle neu erstellt werden.",
          "ru": "Адаптер был перепрограммирован с нуля, а значит, старый конфиг больше не совместим с новой версией. Все станции должны быть созданы заново.",
          "pt": "O adaptador foi reprogramado do zero, o que significa que a configuração antiga já não é compatível com a nova versão. As estações devem ser todas criadas novamente.",
          "nl": "De adapter is helemaal opnieuw geprogrammeerd, waardoor de oude config niet meer compatibel is met de nieuwe versie. De stations moeten allemaal opnieuw worden aangemaakt.",
          "fr": "L'adaptateur a été reprogrammé à partir de zéro, ce qui signifie que l'ancienne configuration n'est plus compatible avec la nouvelle version. Les stations doivent toutes être créées à nouveau.",
          "it": "L'adattatore è stato riprogrammato da zero, il che significa che la vecchia configurazione non è più compatibile con la nuova versione. Le stazioni devono essere create di nuovo.",
          "es": "El adaptador ha sido reprogramado desde cero, lo que significa que la antigua configuración ya no es compatible con la nueva versión. Hay que volver a crear todas las estaciones.",
          "pl": "Adapter został przeprogramowany od nowa, co oznacza, że stara konfiguracja nie jest już kompatybilna z nową wersją. Wszystkie stacje muszą być utworzone od nowa.",
          "uk": "Адаптер було перепрограмовано з нуля, а це означає, що стара конфігурація більше не сумісна з новою версією. Всі станції повинні бути створені заново.",
          "zh-cn": "适配器已经从头开始重新编程，这意味着旧的配置不再与新版本兼容。这些站必须全部重新创建。"
        },
        "link": "https://forum.iobroker.net/topic/60140/tankerk%C3%B6nig-adapter-komplett-umbau",
        "linkText": {
          "en": "please read forum post before update",
          "de": "Bitte lese den Forenbeitrag vor dem Update",
          "ru": "пожалуйста, прочитайте сообщение на форуме перед обновлением",
          "pt": "por favor lê a mensagem do fórum antes de actualizares",
          "nl": "lees a.u.b. de forumpost vóór de update",
          "fr": "S'il te plaît, lis le post du forum avant la mise à jour",
          "it": "Leggi il post del forum prima di aggiornare",
          "es": "por favor, lee el post del foro antes de actualizar",
          "pl": "przeczytaj post na forum przed aktualizacją",
          "uk": "будь ласка, прочитайте повідомлення на форумі перед оновленням",
          "zh-cn": "更新前请阅读论坛帖子"
        },
        "level": "warn",
        "buttons": [
          "agree",
          "cancel"
        ]
      }
    ],
    "messagebox": true,
    "tier": 3,
    "adminUI": {
      "config": "materialize"
    },
    "plugins": {
      "sentry": {
        "dsn": "https://a9e6413d06b64e7e8e8fb892dfd7532e@sentry.iobroker.net/228"
      }
    }
  },
  "native": {
    "synctime": 5,
    "resetValues": false,
    "noLogs": true,
    "apikey": "\u0007\nU\f\u0006V\u0003\u0000\u001e\\VW]NWPP\n\u0019R\u0007\u0002\u0003I\f\u0001UQU[Y\\U\u0001[\u0002",
    "station0": "6197ee84-4a05-4b40-a8f4-e33c07aac90a",
    "stationname0": "SB-Tankstelle",
    "station1": "df9924e6-9ce8-4677-8eb1-63e194db6e15",
    "stationname1": "Markant Bahnhofstr.",
    "station2": "9f8038f4-f6a3-4609-b8c7-5acb232024e6",
    "stationname2": "Shell Grüner Weg",
    "station3": "a2fc501e-5124-46c3-af5e-2b620d1d643e",
    "stationname3": "AVIA Frankfurter Weg",
    "station4": "",
    "stationname4": "",
    "station5": "",
    "stationname5": "",
    "station6": "",
    "stationname6": "",
    "station7": "",
    "stationname7": "",
    "station8": "",
    "stationname8": "",
    "station9": "",
    "stationname9": "",
    "stationsarray": [
      [
        "6197ee84-4a05-4b40-a8f4-e33c07aac90a",
        "SB-Tankstelle"
      ],
      [
        "df9924e6-9ce8-4677-8eb1-63e194db6e15",
        "Markant Bahnhofstr."
      ],
      [
        "9f8038f4-f6a3-4609-b8c7-5acb232024e6",
        "Shell Grüner Weg"
      ],
      [
        "a2fc501e-5124-46c3-af5e-2b620d1d643e",
        "AVIA Frankfurter Weg"
      ],
      [
        "",
        ""
      ],
      [
        "",
        ""
      ],
      [
        "",
        ""
      ],
      [
        "",
        ""
      ],
      [
        "",
        ""
      ],
      [
        "",
        ""
      ]
    ],
    "station": [
      {
        "station": "6197ee84-4a05-4b40-a8f4-e33c07aac90a",
        "stationname": "SB-Tankstelle",
        "discounted": false,
        "discountObj": {
          "discount": 0,
          "fuelType": [
            "e5",
            "e10",
            "diesel"
          ],
          "discountType": "absolute"
        },
        "city": "Paderborn",
        "postCode": "33100",
        "street": "Im Dörener Feld 4"
      },
      {
        "station": "df9924e6-9ce8-4677-8eb1-63e194db6e15",
        "stationname": "Markant Bahnhofstr.",
        "discounted": false,
        "discountObj": {
          "discount": 0,
          "fuelType": [
            "e5",
            "e10",
            "diesel"
          ],
          "discountType": "absolute"
        },
        "street": "Bahnhofstr. 76",
        "city": "Paderborn",
        "postCode": "33102"
      },
      {
        "station": "9f8038f4-f6a3-4609-b8c7-5acb232024e6",
        "stationname": "Shell Grüner Weg",
        "discounted": false,
        "discountObj": {
          "discount": 0,
          "fuelType": [
            "e5",
            "e10",
            "diesel"
          ],
          "discountType": "absolute"
        },
        "street": "Grüner Weg 24",
        "city": "Paderborn",
        "postCode": "33102"
      },
      {
        "station": "a2fc501e-5124-46c3-af5e-2b620d1d643e",
        "stationname": "AVIA Frankfurter Weg",
        "discounted": false,
        "discountObj": {
          "discount": 0,
          "fuelType": [
            "e5",
            "e10",
            "diesel"
          ],
          "discountType": "absolute"
        },
        "street": "Frankfurter Weg 29",
        "city": "Paderborn",
        "postCode": "33102"
      }
    ],
    "combinedOptions": {
      "closed": "Station Closed",
      "noPrice": "No Prices",
      "notFound": "Station Not Found"
    }
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "protectedNative": [
    "apikey"
  ],
  "encryptedNative": [],
  "notifications": [],
  "instanceObjects": [
    {
      "_id": "stations",
      "type": "channel",
      "common": {
        "name": "Gas stations"
      },
      "native": {}
    },
    {
      "_id": "stations.adapterStatus",
      "type": "state",
      "common": {
        "name": "adapter status",
        "desc": "adapter status",
        "type": "string",
        "role": "info.status",
        "def": "idle",
        "read": true,
        "write": false
      },
      "native": {}
    }
  ],
  "objects": [],
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1672413024565
}`

**Comment by guergen1** [comment]
![grafik](https://user-images.githubusercontent.com/34395245/210085673-f3899a7c-959b-4005-85a8-5c9333306f45.png)

**Comment by guergen1** [comment]
Auch die Übersetzung des DP ist lustig: "Postleitzahl des Bahnhofs"

Es handelt sich bei den oberen beiden post´s um die git-Veriosn 3.3.1!

**Comment by xXBJXx** [comment]
Gehe in die Ui und dann auf Bearbeiten der Stationen und mache eine Änderung egal wo z. B. im Namen dann kannst du es wider wegmachen. Jetzt noch auf hinzufügen das bei allen Stationen am Schluss dann noch speichern 
hier noch mal beschrieben https://forum.iobroker.net/topic/60140/tankerk%C3%B6nig-adapter-komplett-umbau/106

**Comment by guergen1** [comment]
Hab ich:
`tankerkoenig.0 | 2022-12-30 16:28:44.431 | info | State value to set for "tankerkoenig.0.stations.cheapest.e10.postCode" has to be type "string" but received type "number"
-- | -- | -- | --
tankerkoenig.0 | 2022-12-30 16:28:44.008 | info | State value to set for "tankerkoenig.0.stations.cheapest.diesel.postCode" has to be type "string" but received type "number"
tankerkoenig.0 | 2022-12-30 16:28:43.889 | info | State value to set for "tankerkoenig.0.stations.cheapest.e5.postCode" has to be type "string" but received type "number"
tankerkoenig.0 | 2022-12-30 16:28:43.648 | info | Start first request
tankerkoenig.0 | 2022-12-30 16:28:41.832 | info | Sync time set to 5 minutes or 300000 ms
tankerkoenig.0 | 2022-12-30 16:28:41.830 | info | Adapter is already in daemon mode
tankerkoenig.0 | 2022-12-30 16:28:41.770 | info | starting.  Version 3.3.1 (non-npm:  iobroker-community-adapters/ioBroker.tankerkoenig#74b28cb39439d083960eb42117bef17ea78baa5b)  in /opt/iobroker/node_modules/iobroker.tankerkoenig, node: v16.19.0,  js-controller: 4.0.24
`

**Comment by guergen1** [comment]
So, jetzt hab ich die Cheapest auch noch gelöscht (alles mit der 3.3.1) will ich mal abwarten

**Comment by guergen1** [comment]
5 Miuten um, neue Werte sind reingekommen: keine neuen Fehler oder Info-Meldungen im Log
