### ISSUE TITLE
[Feature]: Cheapest Station Boolean

### ISSUE THREAD

**Issue by mctom** [iobroker-community-adapters/ioBroker.tankerkoenig#109]
### Is your feature request related to a problem? Please describe.

Marking the cheapest gas station in the visualization.

### Describe the solution you'd like

Create a Boolean datapoint that indicates whether this gas station is the cheapest.

Create datapoint under:
tankerkoenig.0.stations.0.diesel.cheapest

### Describe alternatives you've considered

Processing of the table with the cheapest gas station in the visualization is very complex.

**Comment by xXBJXx** [comment]
The idea is good there is only one problem, it can have several stations of the same price and are thus all cheap.
This would mean that in all stations that have the cheapest price, the state will then stand on true.

**Comment by mctom** [comment]
I think this is no Problem. Then you have differnet stations whit a cheapest Flag in the Visualisation.

**Comment by xXBJXx** [comment]
Ok, then I will implement this

**Comment by xXBJXx** [comment]
Added in version 3.3.2

**Comment by mctom** [comment]
Works very well. Thanks for the fast implementation
