### ISSUE TITLE
wrong object value tankerkoenig.0.stations.*.status resp. no updates for fuel prices until station shop opens, although 24/7 tank automate exists

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.tankerkoenig#114]
I have a fuel station where the opening times only apply fot the shop, but you can 24/7 get fuel with automate.
But the station status is closed and the price isn't updated outside the opening times.
`[{"text":"Mo-Fr","start":"06:00:00","end":"19:00:00"},{"text":"Samstag","start":"08:00:00","end":"16:00:00"}]`

On tankerkoenig website I see at least the correct latest prices for this station, but the adapter shows obsolete prices until the station opens again.

### Describe the solution you'd like

I have tried to set overrideOpeningTimes to "MO-SO 00:00:00 - 23:59:59" or wholeDay=true. But nothing leads to correct status=open and updating prices.

**Comment by Diginix** [comment]
Unfortunately the API doesn't deliver a price if station status is closed. And it is not possible to report the wrong opening times on their website.

**Comment by xXBJXx** [comment]
All state in the adapter are for reading only and not for writing.
You can't change the opening hours with the API.
You could write an email to info@tankerkoenig.de and explain the situation.

**Comment by Diginix** [comment]
For what is the state tankerkoenig.0.stations.0.overrideOpeningTimes if readonly?

**Comment by xXBJXx** [comment]
this is a state with an array of changed opening hours
![image](https://user-images.githubusercontent.com/32600934/211204161-009751e0-c1bf-4220-9763-a01d7027e976.png)
please keep in mind that the states are only updated when creating / editing the station, since this requires a detail query and this cannot be done automatically.

**Comment by Diginix** [comment]
Ok, clear so far and no possibility to solve the problem within the adapter as long as the API doesn't support it.
Thanks.

**Comment by Diginix** [comment]
I have contacted tankerkoenig and they want to check this. In best case they change "wholeday to true" for this station and then the JSON should contain 24/7 the current prices.
