### ISSUE TITLE
JSON wird in Widget nicht angezeigt (evtl. Array nicht definiert?)

### ISSUE THREAD

**Issue by maloross** [iobroker-community-adapters/ioBroker.tankerkoenig#24]
Ich möchte die Tabelle mit dem JSON-Widget in VIS darstellen, es wird aber nichts angezeigt. Im Datenpunkt liegen die Daten in folgendem Format:
`{"ok":true,"license":"CC BY 4.0 -  https:\/\/creativecommons.tankerkoenig.de","data":"MTS-K","prices":{"6d38e242-65c7-4f07-9ed9-73e58796ce50":{"status":"open","e5":1.429,"e10":1.409,"diesel":1.299},"af93b17c-8eba-4245-84dd-9feb83032ab5":{"status":"open","e5":1.439,"e10":1.419,"diesel":1.319},"3eddd11c-8b0a-4075-8509-de79becbf9d3":{"status":"open","e5":1.379,"e10":1.359,"diesel":1.259},"00060788-0004-4444-8888-acdc00000004":{"status":"open","e5":1.364,"e10":1.344,"diesel":1.224},"51d4b4a6-a095-1aa0-e100-80009459e03a":{"status":"open","e5":1.329,"e10":1.309,"diesel":1.179},"51d4b4d3-a095-1aa0-e100-80009459e03a":{"status":"open","e5":1.409,"e10":1.389,"diesel":1.279}}`
Der Standardtext im Widget gibt folgende Struktur vor:
`[{"Title": "first", "Value": 1, "_Description": "Value1"}, {"Title": "second", "Value": 2, "_Description": "Value2"}]`
Die komplette Ausgabe ist mit eckigen Klammern umschlossen. Wie ist das  zu beheben?

**Comment by Pix---** [comment]
Der Datenpunkt JSON liefert einzig die Antwort des Servers auf die Anfrage. Um eine Formatierung für das JSON Widget zu erreichen, ist ein zB ein Javascript nötig, das auf Änderungen des Tankerkönig-Datenpunktes reagiert und dann eine passende Ausgabe generiert.

Ggf. kann man in einer zukünftigen Version des Adapters einen für das VIS-Widget passenden Datenpunkt erzeugen lassen.

Stelle die Frage noch einmal im Forum unter "Skripte", das erhöht die Reichweite unter möglichen Kandidaten, die eine Lösung haben.

**Comment by xXBJXx** [comment]
Der Adapter wurde vollständig umgeschrieben und die JsonTable wurde hinzugefügt neues Release v.3.0.3
