### ISSUE TITLE
Error in saving new tankerkönig api-key

### ISSUE THREAD

**Issue by deniskrafczyk** [iobroker-community-adapters/ioBroker.tankerkoenig#46]
When saving the tankerkoenig API key nothing happens in the UI. 

In the browser console the following error is found:

Uncaught ReferenceError: Invalid left-hand side in assignment
    at save (index_m.html?0:166)
    at HTMLAnchorElement.<anonymous> (adapter-settings.js:196)
    at HTMLAnchorElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLAnchorElement.q.handle (jquery-3.2.1.min.js:3)

This error has its origin in index_m.html:157:

`if (apikey_string.match(patt) === null)`

unfortunately results in false, although my API-key should match the regex pattern, see:

https://regex101.com/r/w9EzeR/2 

Is it possible to implement a workaround there?

**Comment by xCruziX** [comment]
A workaround is to click on the register stations so the save button will be enabled.

**Comment by Pix---** [comment]
Hello @deniskrafczyk,
@xCruziX is right, a workaround is to activate another form field. This issue shows up with other adapter configurations on my system as well.

**Comment by scripthase** [comment]
Hallo zusammen,

bei mir besteht genau das selbe Problem.
Ich trage den API-Key ein, hinterlege auch meine Tankstellen und will alles abspeichern, aber nichts passiert beim Klicken auf Speichern!

Wenn ich auf Abbrechen klicke, dann sagt er, dass alle Änderungen verworfen werden, da man nichts gespeichert hat.

Somit ist es für mich Aktuell leider nicht nutzbar!
Freue mich, wenn das Problem behoben wird.

Vielen lieben Dank.

**Comment by Pix---** [comment]
@scripthase Hast du den allgemeinen Workaround probiert? Erst auf ein anderes Feld klicken, dann auf "Speichern". Welche Version hast du vor deiner Frage installiert?

**Comment by scripthase** [comment]
@Pix--- Was meinst Du mit allgemeinen Workaround? Wo findet man den? Ich habe den API-Key eingetragen, dann auf ein anderes Feld z.B. in Tankstellen geklickt und auf Speichern. Funktioniert trotzdem nicht!

Meine Version ist die, die in den Adaptern angeboten wird. 2.0.5

**Comment by scripthase** [comment]
> @Pix--- Was meinst Du mit allgemeinen Workaround? Wo findet man den? Ich habe den API-Key eingetragen, dann auf ein anderes Feld z.B. in Tankstellen geklickt und auf Speichern. Funktioniert trotzdem nicht!
> 
> Meine Version ist die, die in den Adaptern angeboten wird. 2.0.5

Habe den Fehler gerade gefunden, man musste bei Intervall noch die Zahl eintragen. Dachte dir wäre als Standard drin!

**Comment by deniskrafczyk** [comment]
Gutern Morgen,

bei mir lag das Problem nicht daran, dass der save button disabled war..

Sondern dass nach dem klicken auf den enabled save button einfach nichts passiert ist...
Aber nicht so tragisch, hab die RegEx Abfrage aus der .html genommen und dann gings auch...
Problem ist nur, dass ich jetzt jedes Mal beim neuen Speichern angezegit bekomme, dass der API key ungültig sei.
Aber wenn ich dann auf ignorieren klicke funktioniert er trotzdem tadellos..

Meiner Meinung nach stimmt was mit der Regex Abfrage in index_m.html nicht.

Danke für eure Hilfe!

**Comment by Pix---** [comment]
Hallo @deniskrafczyk,
danke fürs Feedback. Ich empfehle Dir, den Adapter auf dein Github-Konto zu forken und dort die Änderungen vorzunehmen. Dann kannst du jederzeit den Adapter aus deinem Github installieren und musst nicht in der ioBroker Installation editieren.

Das angesprochenen Problem kann ich nicht reproduzieren. In Safari und Chrome und OS X funktioniert die Regex Abfrage. Auch die Regex-Prüfung des Formular Feldes funktioniert (material).

Ich habe gerade die Funktion _Einstellungen sichern_ und _Einstellungen laden_ getestet. Entgegen anderer Erfahrungen, die hier geteilt wurden, hat es bei mir einwandfrei geklappt. Alle StationID und der API Schlüssel wurden zurückgespielt und konnten gespeichert werden. Es ist also einfach möglich, eine zweite Instanz (allerdings von der gleichen Adapterversion) anzulegen, mit den gespeicherten Einstellungen auszustatten und damit zu testen.

@scripthase Wie bei anderen Adaptern auch gibt es häufig ein Belastungsproblem beim Server, wenn alle Clients den gleichen Cron eingestellt haben. Daher habe ich dem User die Wahl gelassen. Ich behaupte: wenn ich den Standardwert vorgebe, ändert ihn keiner anschließend.

**Comment by TeubyDE** [comment]
Gleiche Problem bei mir wie es schon weiter oben beschrieben worden ist.
Ich nutze ein Macbook (Catalina 10.15.4) mit Chrome (Version 81.0.4044.138)

ist sehr frustrierend wenn mal alle 10 Tankstellen rausgesucht hat und dann die Einstellungen verliert....
