### ISSUE TITLE
Rabatt in Preis mit einfließen lassen

### ISSUE THREAD

**Issue by lolax80** [iobroker-community-adapters/ioBroker.tankerkoenig#50]
Hallo,

der Adapter funktioniert perfekt.
Ich komme jedoch bei einer Tankstelle 3cent Rabatt auf den Liter Sprit. Wie kann ich denn die Werte angleichen?

**Comment by Pix---** [comment]
Gute Idee, danke. Werde eine Datenpunkt Rabatt in Cent in die Einstellungen für jede Station einbauen. 

Dauert aber bis zum Update. 

Workaround in VIS:
Nutze ein Binding so oder ähnlich {preis:tankerkoenig.0.RESTDERID;preis-0.03}

Gruß
Pix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lolax80** [comment]
Ich würde gerne einfach wie jetzt auch die günstigste Tankstelle per Datenpunkt auslesen können.
Es sollte hier schon der Rabatt vor dem Eintragen der eigentlichen Werte der Preise berücksichtigt sein.
Also unter Objekt e5 soll gleich der Preis - Rabatt stehen.

Hoffe Du verstehst was ich meine.

Ich lasse aktuell mit einem Skript die Änderung unter günstigste Tankstelle auswerten, was aber wegen dem Rabatt falsch sein kann.

Grüße
Alex

Von meinem iPhone gesendet

**Comment by Pix---** [comment]
Hallo Alex,

ich versteh schon. Der Adapter geht alle eingetragenen Stationen nacheinander durch und holt die Preise von Tankerkoenig ab und speichert sie in die Datenpunkte. Dabei vergleicht er bei jeder Station, ob sie verglichen mit den anderen Stationen nicht günstiger ist. Wenn ja, wird sie auch in Cheapest geschrieben.

Für die Zukunft plane ich daher einen weiteren Number-Datenpunkt "Rabatt", der vor dem Speichern und Vergleichen jeweils ausgelesen und eingerechnet wird. Default ist 0. Zusätzlich kommt noch ein Boolean-Datenpunkt "rabattiert" (true/false), der gesetzt wird, falls "Rabatt" <> 0 ist. Da ist für VIS von Bedeutung.
Weiterhin plane ich einen Boolean-Datenpunkt "isCheapest" innerhalb der Stationen. Das hat mit deinem Hinweis nichts zu tun, ist aber oft gewünscht.

Gruß
Pix

**Comment by ChrisWoehrle** [comment]
Super wäre ein Rabatt auch in %. Wir bekommen hier bspw. 1% Rabatt wenn wir eine Bankkarte von der lokalen vrbank verwenden.

**Comment by xXBJXx** [comment]
Der Adapter wurde vollständig umgeschrieben und eine Rabatt Option wurde hinzugefügt neues Release v.3.0.3

**Comment by ChrisWoehrle** [comment]
Wunderbar.  Wir haben mit der vr Bank Gold card einen Rabatt von 1 % bei einer Tankstelle den man jetzt nicht mehr mit blockly berechnen muss. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 18.11.22, 23:53 schrieb Issi ***@***.***>:

   
  Der Adapter wurde vollständig umgeschrieben und eine Rabatt Option wurde hinzugefügt neues Release v.3.0.3
