### ISSUE TITLE
Feature Request: manuelle Aktualisierung bzw. Abholung der Preise anstoßen 

### ISSUE THREAD

**Issue by Messiahs** [iobroker-community-adapters/ioBroker.tankerkoenig#53]
schön wäre es, wenn man durch setzen eines Datenpunktes die Aktualisierung der Preise anstoßen könnte.
Dieser Datenpunkt sollte dann automatisch nach Verarbeitungsende zurückgesetzt werden.

**Comment by xXBJXx** [comment]
Der Adapter wurde vollständig umgeschrieben und die manuelle Aktualisierung wurde hinzugefügt neues Release v.3.0.3
