### ISSUE TITLE
export jason function not working - nothing happens

### ISSUE THREAD

**Issue by Seqway** [iobroker-community-adapters/ioBroker.tankerkoenig#54]
Hello,
i am migrating to another computer and wanted to use the export function of tankerkoenig.0 but when i click on the button. nothings happens !

tankerkoenig version 2.0.5
nodejs v12.20.0
npm 6.14.8

![grafik](https://user-images.githubusercontent.com/40624961/103477461-698ef180-4dbf-11eb-9b74-e31c57faaa41.png)

**Comment by Pix---** [comment]
Hello,
can not reproduce this issue. Does it work in other adapters settings?
