### ISSUE TITLE
Warnmeldung tankerkönig

### ISSUE THREAD

**Issue by SmartHomie1** [iobroker-community-adapters/ioBroker.tankerkoenig#64]
Moin,
ich habe nach wie vor das Problem mit der folgenden Fehlermeldung:
![Bild1](https://user-images.githubusercontent.com/72092607/117129470-01691000-ad9f-11eb-880b-f83ab987e57c.png)

Da der letzt Bug Report geschlossen wurde, dachte ich, dass evtl. eine Installation der Version 2.0.9 das Problem behebt. Bei mir leider nicht. Die Warnmeldungen kommen mit jeder Aktualisierung der Daten wieder. Node und NPM sind aktuell und den Fixer habe ich auch schon gestartet.

Greetz
Roland

**Comment by Pix---** [comment]
Hallo Roland,

hast du einen upload gemacht?

<img width="465" alt="Bildschirmfoto 2021-05-05 um 12 45 25" src="https://user-images.githubusercontent.com/8090989/117130091-db903b00-ad9f-11eb-987b-f73a828c75f7.png">

Gruß
Pix

**Comment by Pix---** [comment]
Der Fehler wurde in 2.0.11 behoben.

**Comment by SmartHomie1** [comment]
Hi Pix, nein....ich habe die letzte Version im Latest upgedated...das ist 2.0.9. O.k. dann warte ich bis 2.0.11 dort verfügbar ist. Ich vermute, dass Du mit Upload spezielle Updatemöglichkeiten meinst - davon lasse ich als Linux "Profi" lieber die Finger. Es läuft ja, nur im Log stört es mich.
Danke für die Info.

**Comment by Pix---** [comment]
Hallo Roland,
2.0.11 sollte im Latest Repository von ioBroker schon drin sein. Aktuelle beta ist 2.0.12.

Der Upload kann im Admin Reiter "Adapter" gemacht werden. Deshalb der Screenshot. Du suchst den tankerkoenig raus und findest am Ende der Zeile eine Pfeil nach oben. Ist nur ein Knopfdruck.

**Comment by SmartHomie1** [comment]
Schaue ich mir an. Vielen lieben Dank.

 
 

Gesendet: Mittwoch, 05. Mai 2021 um 13:03 Uhr
Von: "Pix" ***@***.***>
An: "Pix---/ioBroker.tankerkoenig" ***@***.***>
Cc: "SmartHomie1" ***@***.***>, "State change" ***@***.***>
Betreff: Re: [Pix---/ioBroker.tankerkoenig] Warnmeldung tankerkönig (#64)


 

Hallo Roland,
2.0.11 sollte im Latest Repository von ioBroker schon drin sein. Aktuelle beta ist 2.0.12.

Der Upload kann im Admin Reiter "Adapter" gemacht werden. Deshalb der Screenshot. Du suchst den tankerkoenig raus und findest am Ende der Zeile eine Pfeil nach oben. Ist nur ein Knopfdruck.

**Comment by SmartHomie1** [comment]
> Hallo Roland,
> 2.0.11 sollte im Latest Repository von ioBroker schon drin sein. Aktuelle beta ist 2.0.12.
> 
> Der Upload kann im Admin Reiter "Adapter" gemacht werden. Deshalb der Screenshot. Du suchst den tankerkoenig raus und findest am Ende der Zeile eine Pfeil nach oben. Ist nur ein Knopfdruck.

Klappt leider nicht. Über den von Dir beschriebenen Weg ist die Version auch 2.0.9

**Comment by HB-F** [comment]
Hier liegt wohl bei der Installation ein Fehler bei der Erstellung der Objekte vor.
Hier das LOG in dem man sieht das es ein Schreibfehler ist:
2021-05-26 15:25:16.898  - info: host.ioBroker_Container iobroker host.ioBroker_Container object tankerkoenig.0.stations.8.diesel created
2021-05-26 15:25:16.927  - info: host.ioBroker_Container iobroker host.ioBroker_Container object tankerkoenig.0.stations.0.e10.combined created
2021-05-26 15:25:16.956  - info: host.ioBroker_Container iobroker host.ioBroker_Container object tankerkoenig.0.stations.8.e10.3rd created
2021-05-26 15:25:16.984  - info: host.ioBroker_Container iobroker host.ioBroker_Container object tankerkoenig.0.stations.8.e10.short created
2021-05-26 15:25:17.013  - info: host.ioBroker_Container iobroker host.ioBroker_Container object tankerkoenig.0.stations.8.e10.feed created
Bei *stations.8.* wird plötzlich für stations.0.e10.combined erzeugt, anstatt dies für Station-8 zu machen.
Wahrscheinlich einfacher Copy and Paste Fehler.

**Comment by Pix---** [comment]
Ich habe das überprüft: beim Anlegen einer weiteren Instanz wird im Log jede Aktion protokolliert und ich kann keinen Fehler finden. Das Anlegen der Objekte muss nicht synchron laufen. Je nach Rechnerleistung und weiteren Einflüssen kann die Reihenfolge sich ändern.
