### ISSUE TITLE
Fehlermeldung Objekttyp existiert nicht

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.tankerkoenig#71]
Hallo,

ich habe gerade den Adapter installiert und eingerichtet.

Beim Start des Adapters erhalte ich folgende Warnmeldung:
`
tankerkoenig.0 | 2021-12-18 18:06:52.224 | warn | This object will not be created in future versions. Please report this to the developer.
tankerkoenig.0 | 2021-12-18 18:06:52.223 | warn | Object tankerkoenig.0.tank is invalid: obj.type has to exist
`

Was ist denn mit der Variable geplant? Kann ich die ggf. löschen?
Wäre ja schön, wenn man den bevorzugten Sprittyp angeben kann und der Adapter gibt auf den Sprittyp bezogen den 1. , 2. und 3. Platz zurück.

**Comment by Siggi0904** [comment]
Das Problem besteht weiterhin, danke.

**Comment by xXBJXx** [comment]
Der Adapter wurde vollständig umgeschrieben, das Problem sollte damit gelöst sein, neues Release v.3.0.3
