### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by docugraf** [iobroker-community-adapters/ioBroker.tankerkoenig#75]
when in admin dark mode the UI is unreadable

![TK-dark](https://user-images.githubusercontent.com/104724022/174006504-acad44a6-ec78-45f4-b1d2-b6042257069b.jpg)

Same image, just in lightmode 5sec later

![tk-light](https://user-images.githubusercontent.com/104724022/174006500-16e5aba4-4627-4065-a105-7b69f4800bc6.jpg)

**Comment by xXBJXx** [comment]
I'm currently working on a complete rebuild of the adapter, it's almost done, as soon as it's done I'll replace the old one. The UI has been completely reworked in the new adapter and a few feature requests have been added, only the documentation is missing. 
![CleanShot 02-07-2022 at 07 19 52](https://user-images.githubusercontent.com/32600934/176987663-22ee82af-b62e-43a1-b224-f040bf7e1cac.png)
