### ISSUE TITLE
[Feature]: Zeitstempel als Datenpunkt

### ISSUE THREAD

**Issue by Chaot1** [iobroker-community-adapters/ioBroker.tankerkoenig#91]
### Is your feature request related to a problem? Please describe.

Ich würde mir gerne den Zeitstempel des tiefsten und des höchsten Preises als separaten Datenpunkt wünschen.
Die Datenpunkte würde ich dann in der Datenbank speichern und bekomme so ein Wochenprofil wann es an welcher Tankstelle üblicherweise zu den günstigsten Preisen kommt und wann man die unbedingt meiden sollte.

**Comment by xXBJXx** [comment]
Soll der Zeitstempel bei jeder Aktualisierung der min / max?
Und in welchem Format soll der Zeitstempel sein?  In den DP `tankerkoenig.0.stations.lastUpdate` ist das Format Epoch ⇨ 1668861935057, das wird dann in den DP von ioBroker umgewandelt in ein Menschenlesbares Format.

**Comment by Chaot1** [comment]
Bei jeder Aktualisierung ist vermutlich einfacher umzusetzen.
Was im Datenpunkt dann steht ist nicht zwingend wichtig. Es geht mir dann um die Aufzeichnung in der Datenbank. Ob ich dann Epoch umwandle oder den Wert als Zahl habe ist, denke ich zunächst egal.

**Comment by xXBJXx** [comment]
Ok dann mache ich es so wie im `tankerkoenig.0.stations.lastUpdate`

**Comment by Schmakus** [comment]
Hätte es nicht nötig gehabt. ;-) Jeder Datenpunkt beinhaltet automatisch die letzte Änderung und letzte Aktualisierung. ;-)
