### ISSUE TITLE
[Feature]: (optionale) Anzeige aller Tankstellen mit dem billigsten Preis im Kanal cheapest

### ISSUE THREAD

**Issue by tobrog** [iobroker-community-adapters/ioBroker.tankerkoenig#93]
### Is your feature request related to a problem? Please describe.

Momentan wird im Kanal cheapest nur eine Tankstelle angezeigt auch wenn mehrere Tankstellen den gleichen billigsten Preis haben. Wäre es möglich, hier (optional) alle Tankstellen mit dem niedrigsten Preis anzeigen zu lassen?

**Comment by Klaus-Lucas** [comment]
Ich habe meine Tankstellen sortiert nach Entfernung eingegeben. Bei gleichen Preisen gibt der Adapter unter Cheapest die letzte Tankstelle aus, die den gleichen Preis hat, also bei mir die weit entfernteste. Eigentlich sollte der Adapter beim Vergleichen feststellen, dass es schon eine Tankstelle mit dem Preis gibt und die folgenden mit gleichem Preis überlesen.
![klu_011](https://user-images.githubusercontent.com/36620907/202993341-656b7f85-5598-4db3-9b34-ac8a9dab01ce.jpg)
![klu_009](https://user-images.githubusercontent.com/36620907/202993363-83f1faab-527d-4e07-bfc4-ea56b3446bae.jpg)
![klu_010](https://user-images.githubusercontent.com/36620907/202993369-a11d7db9-d734-4750-ad44-c785a625c6c9.jpg)

**Comment by xXBJXx** [comment]
Wie genau hast du es dir den vorgestellt? 
Aktuell ist es so:
`cheapest.e5.short`
Hauptordner ⇨ `cheapest` ⇨ Kraftstoffarten ⇨ `e5` ⇨ Datenpunkt ⇨ `short`

Unter Kraftstoffarten ⇨ `e5` sind alle Datenpunkte für eine Station (name, station_id, usw.) drinnen.
Da kann ich nicht für alle Stationen, die den gleichen Preis haben, Datenpunkte erstellen, da das viel zu unübersichtlich werden kann. 

Bitte ein Beispiel

**Comment by tobrog** [comment]
Ich hatte eher daran gedacht, dass der Datenpunkt "name" oder wahrscheinlich besser ein seperater neuer Datenpunkt zb `cheapest.e5.list` oder `cheapest.e5.cheapest_stations` eine Liste (zb als json) mit Namen aller Stationen enthält, die den gleichen niedrigsten Preis haben.  Wäre dann nur ein zusätzlicher Datenpunkt.

**Comment by xXBJXx** [comment]
Also so in etwa:
`cheapest.e5.cheapest_stations`
Hauptordner ⇨ `cheapest` ⇨ Kraftstoffarten ⇨ `e5` ⇨ Datenpunkt ⇨ `cheapest_stations` Inhalt von `cheapest_stations` = `["Shell","ESSO","ARAL"]`

**Comment by tobrog** [comment]
Ja, in etwa. Falls möglich aber lieber in diesem Format: 
`[{"name": "Shell"}, {"name": "ESSO"}, {"name": "ARAL"}]`
Lässt sich dann besser weiterverarbeiten  ;-)

**Comment by xXBJXx** [comment]
![image](https://user-images.githubusercontent.com/32600934/204044768-b9f9ccfc-add4-488e-9e6a-b7d17646ed95.png)

so gut

**Comment by xXBJXx** [comment]
Wenn du willst, kannst du die Testversion von GitHub installieren und testen, ob alles so funktioniert wie es soll.

**Comment by tobrog** [comment]
Vielen Dank. Hab die GitHub Version jetzt installiert, aber der Datenpunkt erscheint nicht. Wird der nur erstellt, wenn mehrere Stationen den gleichen niedrigsten Preis haben? Momentan ist das bei mir nur eine Station.

**Comment by xXBJXx** [comment]
Er sollte nach einem Start / Neustart vom Adapter erstellt werden.
Habe es auf meinem Testsystem versucht und er wurde beim Neustart angelegt.

**Comment by tobrog** [comment]
Anscheinend hat das installieren der Github Version nicht geklappt, obwohl es in iob fehlerlos durchgelaufen ist. 

`$ iobroker url https://github.com/iobroker-community-adapters/ioBroker.tankerkoenig --host raspberrypi --debug
install iobroker-community-adapters/ioBroker.tankerkoenig#7b2a64302018fa3e4f7641ed3e817ce3b5a307bc
NPM version: 8.19.2Installing iobroker-community-adapters/ioBroker.tankerkoenig#7b2a64302018fa3e4f7641ed3e817ce3b5a307bc... (System call)
upload [4] tankerkoenig.admin /opt/iobroker/node_modules/iobroker.tankerkoenig/admin/build/index.js build/index.js application/javascript
upload [3] tankerkoenig.admin /opt/iobroker/node_modules/iobroker.tankerkoenig/admin/build/index.js.map build/index.js.map application/json
upload [2] tankerkoenig.admin /opt/iobroker/node_modules/iobroker.tankerkoenig/admin/index_m.html index_m.html text/html
upload [1] tankerkoenig.admin /opt/iobroker/node_modules/iobroker.tankerkoenig/admin/style.css style.css text/css
upload [0] tankerkoenig.admin /opt/iobroker/node_modules/iobroker.tankerkoenig/admin/tankerkoenig.png tankerkoenig.png image/png
Process exited with code 0`

Das steht im iob log

`<html>
<body>


tankerkoenig.0 | 2022-11-26 17:53:25.198 | info | Sync time set to 5 minutes or 300000 ms
-- | -- | -- | --
tankerkoenig.0 | 2022-11-26 17:53:25.040 | info | starting. Version 3.0.6 (non-npm: iobroker-community-adapters/ioBroker.tankerkoenig#7b2a64302018fa3e4f7641ed3e817ce3b5a307bc) in /opt/iobroker/node_modules/iobroker.tankerkoenig, node: v16.18.1, js-controller: 4.0.23
tankerkoenig.0 | 2022-11-26 17:53:12.457 | error | requestData error: Error: DB closed stack: Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25) at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:657:40) at Tankerkoenig.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5880:35)
tankerkoenig.0 | 2022-11-26 17:53:12.455 | warn | get state error: Connection is closed.
tankerkoenig.0 | 2022-11-26 17:53:12.317 | error | writeState error: Error: DB closed stack: Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25) at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:657:40) at Tankerkoenig.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5880:35)
tankerkoenig.0 | 2022-11-26 17:53:12.312 | warn | get state error: Connection is closed.
tankerkoenig.0 | 2022-11-26 17:53:12.254 | info | terminating with timeout
tankerkoenig.0 | 2022-11-26 17:53:11.912 | warn | redis get tankerkoenig.0.stations.0.e10.minmax.feed_max, error - DB closed
tankerkoenig.0 | 2022-11-26 17:53:11.252 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
tankerkoenig.0 | 2022-11-26 17:53:11.251 | info | terminating
tankerkoenig.0 | 2022-11-26 17:53:10.947 | info | Got terminate signal TERMINATE_YOURSELF
tankerkoenig.0 | 2022-11-26 17:53:10.735 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>`

**Comment by xXBJXx** [comment]
hmm seltsam aber ok da gab es ohnehin noch einen kleinen Fehler da wurde der state an zufielen, stellen erstellt ich mache heute noch ein Fix fertig

**Comment by tobrog** [comment]
OK, danke

**Comment by xXBJXx** [comment]
ok ist auf GitHub verfügbar bitte testen jetzt sollte auch der Name dann angezeigt werden, wen nur 1ne Station eingetragen ist

**Comment by tobrog** [comment]
Super, vielen Dank. Datenpunkt wird jetzt angezeigt.

**Comment by xXBJXx** [comment]
Ok dann werde ich morgen auf neuen Release machen.
