### ISSUE TITLE
[Feature]: Ranking Cheapest Station

### ISSUE THREAD

**Issue by Klaus-Lucas** [iobroker-community-adapters/ioBroker.tankerkoenig#96]
### Is your feature request related to a problem? Please describe.

Laut [Issue 50](https://github.com/iobroker-community-adapters/ioBroker.tankerkoenig/issues/50#issuecomment-689804317)
Der Adapter geht alle eingetragenen Stationen nacheinander durch und holt die Preise von Tankerkoenig ab und speichert sie in die Datenpunkte. Dabei vergleicht er bei jeder Station, ob sie verglichen mit den anderen Stationen nicht günstiger ist. Wenn ja, wird sie auch in Cheapest geschrieben.

Ich habe meine Tankstellen sortiert nach Entfernung eingegeben. Bei gleichen Preisen gibt der Adapter unter Cheapest (s.o.) die letzte Tankstelle aus, die den gleichen Preis hat, also bei mir die weit entfernteste. Meiner Meinung nach sollte der Adapter beim Vergleichen feststellen, dass es schon eine Tankstelle mit dem Preis gibt und die folgenden mit gleichem Preis ignorieren.

![klu_011](https://user-images.githubusercontent.com/36620907/202996759-92cdc998-bdf7-45fd-bf82-60a48696523c.jpg)
![klu_009](https://user-images.githubusercontent.com/36620907/202996767-84baa351-6b88-413d-88c9-56fe82a32f5a.jpg)
![klu_010](https://user-images.githubusercontent.com/36620907/202996776-d41b11b5-f3ad-4584-95e6-eb6f15dc7985.jpg)

Ich persönlich fände ich es noch gut, wenn der Short Preis gerundet ausgegeben würde, also bei 1,879€ 1,88€. Ist aber Ansichtssache.

**Comment by Schmakus** [comment]
Muss man sich mal anschauen mit "Erste günstige Tankstelle".
Was die Preisrundung angeht: Der short-Preis ist nix anderes, als der um eine Stelle gekürzte Preis, welcher zusammen mit dem 3rd Datenpunkt wieder zu einem "Tankstellenpreis" gemacht werden kann. (siehe combined).
Ansonsten ist es natürlich eine Ansichtssache, jedoch ist umgangssprachlich der Preis an einer Tankstelle der Preis ohne die letzte Stelle. Bei 1.889 € sagt niemand, dass der Preis bei 1.89 € liegt, sondern immer 1.88 €

**Comment by Klaus-Lucas** [comment]
"Bei 1.889 € sagt niemand, dass der Preis bei 1.89 € liegt, sondern immer 1.88 €"
Das genau ist ja das Ziel der Ölkonzerne, weil diese Art Preisdarstellung vorteilhafter für sie ist :-) 

"generell entscheidet, dass nur Stationen, die günstiger sind, als die bisher Günstigste, selbst Günstigste werden können"
Würde ich bevorzugen.

**Comment by xXBJXx** [comment]
>Ich persönlich fände ich es noch gut, wenn der Short Preis gerundet ausgegeben würde, also bei 1,879€ 1,88€. Ist aber Ansichtssache.

Eine Rundung des Preises im `short` Datenpunkt werde ich nicht einbauen. 
Man könnte eventuell darüber nachdenken / diskutieren, ob man einen neuen Datenpunkt `rounded` einbaut. Falls erwünscht, dann bitte ein Feature Request dafür erstellen. 

----

>Ich habe meine Tankstellen sortiert nach Entfernung eingegeben. Bei gleichen Preisen gibt der Adapter unter Cheapest (s.o.) die letzte Tankstelle aus, die den gleichen Preis hat, also bei mir die weit entfernteste. Meiner Meinung nach sollte der Adapter beim Vergleichen feststellen, dass es schon eine Tankstelle mit dem Preis gibt und die folgenden mit gleichem Preis ignorieren.

Ich habe mir heute noch mal den Response von der API angeschaut und gesehen, dass die Stationen dort nicht in der Reihenfolge, wie sie in der UI konfiguriert sind zurückkommen.

Reihenfolge UI
`0 = a5d9021e-7833-41e7-abe5-b2d99e7623ba`
`1 = b37bbb94-30a6-4c84-ba09-56d9d318b9f8`
`2 = 00545000-fa12-4f42-a991-8e3556c24db3`
`3 = f9e2db4d-a0b0-481d-97c5-f1953ed63657`
`4 = e1a15081-25d9-9107-e040-0b0a3dfe563c`

Reihenfolge Response 
![image](https://user-images.githubusercontent.com/32600934/203939130-1700a9aa-ff86-4d6c-ae1e-9297e02a0dc4.png)


Darauf wird dann die Sortierung angewandt  (e5 Sortierung).
![image](https://user-images.githubusercontent.com/32600934/203939946-e64a5abe-4d4a-45e0-bf67-4db778441977.png)

Und angesichts dessen wird, auch wenn die 1. Tankstelle, die in der UI konfiguriert ist und gerade einer der Tankstellen mit dem billigsten Preisen ist, nicht als Erstes angezeigt wird.

Ich werde was einbauen, dass der Response nach der Reihenfolge der Stationen in der UI sortiert wird und dann erst nach den Preisen. Jetzt sollten die billigsten Tankstellen nach der UI Reihenfolge angezeigt werden.
![image](https://user-images.githubusercontent.com/32600934/203937002-af75f549-4b45-4e0d-9a85-8aeea798a1b5.png)

Ist das so OK für dich?

**Comment by Klaus-Lucas** [comment]
@xXBJXx auf jeden Fall. Danke für die Mühe.
Wegen des Short Preis: Lasst es wie es ist. Ein weiterer Datenpunkt Rounded ist die bessere Lösung.

**Comment by xXBJXx** [comment]
@Klaus-Lucas Ich habe auf GitHub eine Testversion mit der neuen sortier Funktion hochgeladen kannst du sie bitte testen und mir dann Bescheid geben, ob sie bei dir so funktioniert wie du sie haben wolltest?

**Comment by Klaus-Lucas** [comment]
@xXBJXx Sieht korrekt aus. Wie geschrieben sind die Tankstellen nach Prio 0-8 eingetragen.
Erst Markant (0), PM (1), Jet (3).... Alle 3 haben den gleichen Preis und in Cheapest steht die Markant.
![klu_004](https://user-images.githubusercontent.com/36620907/204051427-ec6c26c4-e154-4db2-a2a0-7826c29a4a76.jpg)
![klu_005](https://user-images.githubusercontent.com/36620907/204051440-b322331b-6d47-498e-a783-0f9422af79a9.jpg)
![klu_006](https://user-images.githubusercontent.com/36620907/204051450-2dbb3893-0bf3-470e-8b93-b044727ac1fc.jpg)

![klu_007](https://user-images.githubusercontent.com/36620907/204051461-14147f8a-5899-4274-bb46-6d5e1c2943c2.jpg)

**Comment by xXBJXx** [comment]
Also so wie es soll?
In der neusten Version auf GitHub ist noch ein neuer state `cheapest_stations` dazu gekommen, in dem alle billigen Stationen mit Namen eingetragen sind.

**Comment by Klaus-Lucas** [comment]
@xXBJXx Danke für die Anpassung.
