### ISSUE TITLE
Was mir noch fehlt... Adressangaben

### ISSUE THREAD

**Issue by 12audi** [iobroker-community-adapters/ioBroker.tankerkoenig#98]
### Is your feature request related to a problem? Please describe.

Moinsen,
hab gerade die Version 3.1.0 installiert... vielen Dank für die Arbeit. 
Was mir aufgefallen ist, zur "alten" Version, ist die Benamung der einzelnen Tankstellen, wie PLZ, Ort, Strasse Hausnummer.
Oder das Beschriftungsfeld erweitern, das ich mir selber die passende Adresse eintragen kann. 
Vielen Dank nochmal für die ganze Arbeit!!

VG
Frank

**Comment by xXBJXx** [comment]
Meist du das jetzt für die UI oder in den Objekten ?

**Comment by 12audi** [comment]
Für die Objekte der einzelnen Tankstellen


Mit freundlichen Grüßen

Frank Reichert

**Comment by xXBJXx** [comment]
Da habe ich vor, das beim ersten Start vom Adapter von der Tankstelle abzufragen, da die Stationen das auch anbieten.
Sobald ich etwas Zeit dazu habe, werde ich das Einbauen.

Ich schaue es mir dann mal an, ob es sinnvoll ist, dass alle in den Namen reinzumachen, dass kann Unterumstände sehr viel sein, sodass der name nicht mehr vollständig angezeigt wird.

**Comment by 12audi** [comment]
super.... war ja nur eine Idee. In der alten Version gab es diese Datenfelder in den Objekten

**Comment by xXBJXx** [comment]
Ist das so okay für den Namen 
![image](https://user-images.githubusercontent.com/32600934/209442870-272a5626-b986-4682-b876-ec1793950b3a.png)
zusätzlich sind noch die neuen states 
![image](https://user-images.githubusercontent.com/32600934/209442909-1e684a01-75e0-4479-aefc-8ea9f805707b.png)

**Comment by 12audi** [comment]
ich bin vonne Socken.... wie fix das geht.
Sieht super aus!!! Danke

VG
Frank

**Comment by xXBJXx** [comment]
Die neue Version ist erst ein mal nur in latest verfügbar, damit es getestet werden kann, wenn alles stabil läuft, kommt es in stable

**Comment by 12audi** [comment]
Dort finde ich sie leider nicht.... Hab umgestellt auf auf latest und nach Tankerkönig gesucht.

<img width="1004" alt="Bildschirmfoto 2022-12-24 um 21 32 41" src="https://user-images.githubusercontent.com/88907267/209450352-ce43e720-04e1-4422-95b3-380b32dbfb53.png">

**Comment by xXBJXx** [comment]
das dauert immer etwas, bis ioBroker die neuen Versionen in die Repo aufnimmt, probier es morgen, dann sollte es drin sein

**Comment by 12audi** [comment]
ok... Danke!!!

**Comment by xXBJXx** [comment]
Hallo @12audi,
ich musste die Detailabfrage aus dem Adapter wider entfernen, da es immer wieder Probleme mit dem server gab.
Ich habe in der UI neue Felder für die Eingabe der Adresse hinzugefügt, wenn diese ausgefüllt werden wird die Adresse dann genauso wie jetzt in den Namen geschrieben und in die states.
Neuer Release 3.2.3 sollte morgen früh im latest sein.

**Comment by 12audi** [comment]
ok..
